apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crm

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - app-deployment.yaml
  - app-service.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/name: crm
    includeSelectors: true
