apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crm-ingress
  namespace: crm
spec:
  rules:
    - host: crm.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: crm-app
                port:
                  number: 8000
