apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crm

resources:
  - ../../base

# Dev image tag and replica count
images:
  - name: crm-app:latest
    newName: sorianfr/project1-app
    newTag: dev

patches:
  - path: deployment-patch.yaml
  - path: ingress-patch.yaml
  - path: postgres-resources-patch.yaml

replicas:
  - name: crm-app
    count: 1
